name: assignment_14
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shimmer_animation: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lucide_icons: ^0.257.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
